config/routes.rb
Taim::Application.routes.draw do
  resources :posts

  resources :seconds

  resources :mains
 root :to => "posts#new"

end

app/models/main.rb
class Main < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base

  attr_accessible :avatar, :name, :title, :content
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }

end

app/models/second.rb
class Second < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  # GET /mains
  # GET /mains.xml
  def index
    @mains = Main.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @mains }
    end
  end

  # GET /mains/1
  # GET /mains/1.xml
  def show
    @main = Main.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @main }
    end
  end

  # GET /mains/new
  # GET /mains/new.xml
  def new
    @main = Main.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @main }
    end
  end

  # GET /mains/1/edit
  def edit
    @main = Main.find(params[:id])
  end

  # POST /mains
  # POST /mains.xml
  def create
    @main = Main.new(params[:main])

    respond_to do |format|
      if @main.save
        format.html { redirect_to(@main, :notice => 'Main was successfully created.') }
        format.xml  { render :xml => @main, :status => :created, :location => @main }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @main.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mains/1
  # PUT /mains/1.xml
  def update
    @main = Main.find(params[:id])

    respond_to do |format|
      if @main.update_attributes(params[:main])
        format.html { redirect_to(@main, :notice => 'Main was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @main.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mains/1
  # DELETE /mains/1.xml
  def destroy
    @main = Main.find(params[:id])
    @main.destroy

    respond_to do |format|
      format.html { redirect_to(mains_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.create( params[:post] )
#    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/seconds_controller.rb
class SecondsController < ApplicationController
  # GET /seconds
  # GET /seconds.xml
  def index
    @seconds = Second.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @seconds }
    end
  end

  # GET /seconds/1
  # GET /seconds/1.xml
  def show
    @second = Second.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @second }
    end
  end

  # GET /seconds/new
  # GET /seconds/new.xml
  def new
    @second = Second.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @second }
    end
  end

  # GET /seconds/1/edit
  def edit
    @second = Second.find(params[:id])
  end

  # POST /seconds
  # POST /seconds.xml
  def create
    @second = Second.new(params[:second])

    respond_to do |format|
      if @second.save
        format.html { redirect_to(@second, :notice => 'Second was successfully created.') }
        format.xml  { render :xml => @second, :status => :created, :location => @second }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @second.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /seconds/1
  # PUT /seconds/1.xml
  def update
    @second = Second.find(params[:id])

    respond_to do |format|
      if @second.update_attributes(params[:second])
        format.html { redirect_to(@second, :notice => 'Second was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @second.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /seconds/1
  # DELETE /seconds/1.xml
  def destroy
    @second = Second.find(params[:id])
    @second.destroy

    respond_to do |format|
      format.html { redirect_to(seconds_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/seconds_helper.rb
module SecondsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taim</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mains/_form.html.erb
<%= form_for(@main) do |f| %>
  <% if @main.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@main.errors.count, "error") %> prohibited this main from being saved:</h2>

      <ul>
      <% @main.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mains/edit.html.erb
<h1>Editing main</h1>

<%= render 'form' %>

<%= link_to 'Show', @main %> |
<%= link_to 'Back', mains_path %>

app/views/mains/index.html.erb
<h1>Listing mains</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mains.each do |main| %>
  <tr>
    <td><%= link_to 'Show', main %></td>
    <td><%= link_to 'Edit', edit_main_path(main) %></td>
    <td><%= link_to 'Destroy', main, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Main', new_main_path %>

app/views/mains/new.html.erb
<h1>New main</h1>

<%= render 'form' %>

<%= link_to 'Back', mains_path %>

app/views/mains/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_main_path(@main) %> |
<%= link_to 'Back', mains_path %>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :multipart => true } do |f| %>
  <%= f.file_field :avatar %>
<%# end %>
<%#= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :style=>'border: 14px solid; color:red;', :class=>'abc'%>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>
<%#= form_for @post, :url => posts_path, :html => { :multipart => true } do |form| %>
  <%#= form.file_field :avatar %>
<%# end %>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>
<%#= form_for @post, :url => posts_path, :html => { :multipart => true } do |form| %>
  <%#= form.file_field :avatar %>
<%# end %>
<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>
<%= image_tag @post.avatar.url %>
<%= image_tag @post.avatar.url(:medium) %>
<%= image_tag @post.avatar.url(:thumb) %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/seconds/_form.html.erb
<%= form_for(@second) do |f| %>
  <% if @second.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@second.errors.count, "error") %> prohibited this second from being saved:</h2>

      <ul>
      <% @second.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seconds/edit.html.erb
<h1>Editing second</h1>

<%= render 'form' %>

<%= link_to 'Show', @second %> |
<%= link_to 'Back', seconds_path %>

app/views/seconds/index.html.erb
<h1>Listing seconds</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @seconds.each do |second| %>
  <tr>
    <td><%= link_to 'Show', second %></td>
    <td><%= link_to 'Edit', edit_second_path(second) %></td>
    <td><%= link_to 'Destroy', second, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Second', new_second_path %>

app/views/seconds/new.html.erb
<h1>New second</h1>

<%= render 'form' %>

<%= link_to 'Back', seconds_path %>

app/views/seconds/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_second_path(@second) %> |
<%= link_to 'Back', seconds_path %>